/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.27.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type ExecuteMsg = {
  increment: {};
} | {
  reset: {
    count: number;
  };
};
export interface InstantiateMsg {
  count: number;
}
export type QueryMsg = {
  get_count: {};
};
export interface GetCountResponse {
  count: number;
}