/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.27.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type ExecuteMsg = {
  receive_ibc_response: ReceiveIbcResponseMsg;
};
export type Binary = string;
export type Timestamp = Uint64;
export type Uint64 = string;
export type Addr = string;
export interface ReceiveIbcResponseMsg {
  msg: IbcPacketAckMsg;
  [k: string]: unknown;
}
export interface IbcPacketAckMsg {
  acknowledgement: IbcAcknowledgement;
  original_packet: IbcPacket;
  relayer: Addr;
  [k: string]: unknown;
}
export interface IbcAcknowledgement {
  data: Binary;
  [k: string]: unknown;
}
export interface IbcPacket {
  data: Binary;
  dest: IbcEndpoint;
  sequence: number;
  src: IbcEndpoint;
  timeout: IbcTimeout;
  [k: string]: unknown;
}
export interface IbcEndpoint {
  channel_id: string;
  port_id: string;
  [k: string]: unknown;
}
export interface IbcTimeout {
  block?: IbcTimeoutBlock | null;
  timestamp?: Timestamp | null;
  [k: string]: unknown;
}
export interface IbcTimeoutBlock {
  height: number;
  revision: number;
  [k: string]: unknown;
}
export interface IbcQueryResultResponse {
  last_update_time: Timestamp;
  response: IbcPacketAckMsg;
  [k: string]: unknown;
}
export interface InstantiateMsg {
  [k: string]: unknown;
}
export type QueryMsg = {
  latest_query_result: {
    channel_id: string;
    [k: string]: unknown;
  };
};